language: objective-c
osx_image: xcode8.3
xcode_workspace: Tsukuba-iOS.xcworkspace
xcode_scheme: Tsukuba-iOS

before_install:
  - pod repo update

pods: remove_debug_pods
pods:
  rm -rf Pods
  bundle install
  bundle exec pod install

build:
  set -o pipefail && xcodebuild -workspace "Tsukuba-iOS.xcworkspace" -scheme "Tsukuba-iOS" -sdk iphonesimulator -destination 'name=iPhone 6' build CODE_SIGNING_REQUIRED=NO | xcpretty -c
